services:
  producer:
    image: vepo/rabbitmq/producer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USR: user
      RABBITMQ_PWD: password
    depends_on:
      - rabbitmq
  consumer:
    image: vepo/rabbitmq/consumer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USR: user
      RABBITMQ_PWD: password
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 8080:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password